import type { AuthUser } from "@/types/auth";
import type { Room, Hostel } from "@/types/hostel";
import type { Resident } from "@/types/resident";
import type { Payment } from "@/types/subscription";

export const MOCK_OWNER_FREE: AuthUser = {
  id: "u-owner-1",
  name: "Aashish Sharma",
  email: "owner@sunrisehostel.com",
  phone: "9841000001",
  role: "HOSTEL_OWNER",
  hostelId: "h-1",
  hostelName: "Sunrise Boys Hostel",
  subscription: {
    plan: "FREE",
    status: "ACTIVE",
    residentsUsed: 10,
    residentsLimit: 10,
    renewsAt: "2026-10-01",
    startedAt: "2026-06-01",
  },
};

export const MOCK_RESIDENTS: Resident[] = [
  {
    id: "r-1",
    name: "Ramesh Adhikari",
    email: "ramesh@mail.com",
    phone: "9841111111",
    roomNumber: "201",
    bedNumber: "B1",
    floor: 2,
    paymentStatus: "PAID",
    status: "ACTIVE",
    joinedDate: "2026-01-12",
    monthlyRent: 12000,
  },
  {
    id: "r-2",
    name: "Sita Karki",
    email: "sita@mail.com",
    phone: "9841222222",
    roomNumber: "202",
    bedNumber: "A2",
    floor: 2,
    paymentStatus: "PENDING",
    status: "ACTIVE",
    joinedDate: "2026-02-03",
    monthlyRent: 12500,
  },
  {
    id: "r-3",
    name: "Bibek Thapa",
    email: "bibek@mail.com",
    phone: "9841333333",
    roomNumber: "101",
    bedNumber: "A1",
    floor: 1,
    paymentStatus: "OVERDUE",
    status: "ACTIVE",
    joinedDate: "2025-11-20",
    monthlyRent: 11000,
  },
  {
    id: "r-4",
    name: "Anisha Rai",
    email: "anisha@mail.com",
    phone: "9841444444",
    roomNumber: "204",
    bedNumber: "B2",
    floor: 2,
    paymentStatus: "PAID",
    status: "ACTIVE",
    joinedDate: "2026-03-15",
    monthlyRent: 13000,
  },
  {
    id: "r-5",
    name: "Kamal Basnet",
    email: "kamal@mail.com",
    phone: "9841555555",
    roomNumber: "103",
    bedNumber: "C1",
    floor: 1,
    paymentStatus: "PAID",
    status: "ACTIVE",
    joinedDate: "2026-04-01",
    monthlyRent: 11000,
  },
  {
    id: "r-6",
    name: "Pooja Maharjan",
    email: "pooja@mail.com",
    phone: "9841666666",
    roomNumber: "205",
    bedNumber: "A1",
    floor: 2,
    paymentStatus: "PENDING",
    status: "ACTIVE",
    joinedDate: "2026-05-10",
    monthlyRent: 12500,
  },
  {
    id: "r-7",
    name: "Dipesh Shrestha",
    email: "dipesh@mail.com",
    phone: "9841777777",
    roomNumber: "102",
    bedNumber: "B1",
    floor: 1,
    paymentStatus: "PAID",
    status: "ACTIVE",
    joinedDate: "2026-01-28",
    monthlyRent: 11500,
  },
  {
    id: "r-8",
    name: "Nirmala Gurung",
    email: "nirmala@mail.com",
    phone: "9841888888",
    roomNumber: "206",
    bedNumber: "A2",
    floor: 2,
    paymentStatus: "PAID",
    status: "ACTIVE",
    joinedDate: "2026-02-19",
    monthlyRent: 13000,
  },
];

export const MOCK_ROOMS: Room[] = [
  {
    id: "rm-101",
    roomNumber: "101",
    floor: 1,
    type: "DOUBLE",
    capacity: 2,
    occupied: 2,
    monthlyRent: 11000,
    status: "FULL",
    amenities: ["Wifi", "Hot water"],
  },
  {
    id: "rm-102",
    roomNumber: "102",
    floor: 1,
    type: "TRIPLE",
    capacity: 3,
    occupied: 2,
    monthlyRent: 11500,
    status: "AVAILABLE",
    amenities: ["Wifi", "Balcony"],
  },
  {
    id: "rm-103",
    roomNumber: "103",
    floor: 1,
    type: "DOUBLE",
    capacity: 2,
    occupied: 1,
    monthlyRent: 11000,
    status: "AVAILABLE",
    amenities: ["Wifi"],
  },
  {
    id: "rm-201",
    roomNumber: "201",
    floor: 2,
    type: "DOUBLE",
    capacity: 2,
    occupied: 2,
    monthlyRent: 12000,
    status: "FULL",
    amenities: ["Wifi", "Attached bath"],
  },
  {
    id: "rm-202",
    roomNumber: "202",
    floor: 2,
    type: "TRIPLE",
    capacity: 3,
    occupied: 2,
    monthlyRent: 12500,
    status: "AVAILABLE",
    amenities: ["Wifi"],
  },
  {
    id: "rm-204",
    roomNumber: "204",
    floor: 2,
    type: "DOUBLE",
    capacity: 2,
    occupied: 2,
    monthlyRent: 13000,
    status: "FULL",
    amenities: ["Wifi", "AC"],
  },
  {
    id: "rm-205",
    roomNumber: "205",
    floor: 2,
    type: "DOUBLE",
    capacity: 2,
    occupied: 1,
    monthlyRent: 12500,
    status: "AVAILABLE",
    amenities: ["Wifi"],
  },
  {
    id: "rm-206",
    roomNumber: "206",
    floor: 2,
    type: "DOUBLE",
    capacity: 2,
    occupied: 1,
    monthlyRent: 13000,
    status: "MAINTENANCE",
    amenities: ["Wifi"],
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "p-1",
    residentName: "Ramesh Adhikari",
    residentId: "r-1",
    amount: 12000,
    method: "ESEWA",
    status: "COMPLETED",
    date: "2026-09-02",
    month: "Sep 2026",
  },
  {
    id: "p-2",
    residentName: "Sita Karki",
    residentId: "r-2",
    amount: 12500,
    method: "KHALTI",
    status: "PENDING",
    date: "2026-09-05",
    month: "Sep 2026",
  },
  {
    id: "p-3",
    residentName: "Bibek Thapa",
    residentId: "r-3",
    amount: 11000,
    method: "CASH",
    status: "OVERDUE",
    date: "2026-08-10",
    month: "Aug 2026",
  },
  {
    id: "p-4",
    residentName: "Anisha Rai",
    residentId: "r-4",
    amount: 13000,
    method: "BANK",
    status: "COMPLETED",
    date: "2026-09-01",
    month: "Sep 2026",
  },
  {
    id: "p-5",
    residentName: "Kamal Basnet",
    residentId: "r-5",
    amount: 11000,
    method: "CASH",
    status: "COMPLETED",
    date: "2026-08-28",
    month: "Aug 2026",
  },
];

export const MOCK_HOSTELS: Hostel[] = [
  {
    id: "h-1",
    name: "Sunrise Boys Hostel",
    address: "Putalisadak, Kathmandu",
    city: "Kathmandu",
    phone: "01-4445555",
    email: "info@sunrise.com",
    totalRooms: 24,
    totalBeds: 72,
    occupiedBeds: 58,
    status: "ACTIVE",
    ownerName: "Aashish Sharma",
  },
  {
    id: "h-2",
    name: "Green Valley Girls Hostel",
    address: "Lakeside, Pokhara",
    city: "Pokhara",
    phone: "061-555666",
    email: "hello@greenvalley.com",
    totalRooms: 18,
    totalBeds: 54,
    occupiedBeds: 49,
    status: "ACTIVE",
    ownerName: "Mina KC",
  },
  {
    id: "h-3",
    name: "City Nest Hostel",
    address: "New Baneshwor, Kathmandu",
    city: "Kathmandu",
    phone: "01-5557777",
    email: "stay@citynest.com",
    totalRooms: 30,
    totalBeds: 90,
    occupiedBeds: 31,
    status: "PENDING",
    ownerName: "Rabin Shrestha",
  },
];

export const MOCK_ANNOUNCEMENTS = [
  {
    id: "a-1",
    title: "Water tank cleaning on Sunday",
    body: "Water supply will pause 9–11 AM. Please store water.",
    date: "2026-09-08",
    tag: "Maintenance",
  },
  {
    id: "a-2",
    title: "September rent due by 10th",
    body: "Please clear September dues to avoid late fees.",
    date: "2026-09-03",
    tag: "Finance",
  },
  {
    id: "a-3",
    title: "New WiFi routers on floor 2",
    body: "Faster 5GHz network HG-5G is now live.",
    date: "2026-08-29",
    tag: "Facility",
  },
];
